### ISSUE TITLE
Cannot access the data

### ISSUE THREAD

**Issue by GalAvineri** [shichaoy/pop_up_slam#5]
Hello :)
First of all, thank you for publishing this github repository!

I am trying to follow the installation guide that you posted and I was stuck in the step called 'Download data'.

When running the command ```sh download_data.sh``` I got the following output:
```
mkdir: cannot create directory ‘pop_planar_slam/dataset’: File exists
--2019-01-12 20:55:19--  http://www.frc.ri.cmu.edu/~syang/dataset/iros_pop_slam_16/tum_far_preproc_tf.bag
Resolving www.frc.ri.cmu.edu (www.frc.ri.cmu.edu)... 128.2.205.32
Connecting to www.frc.ri.cmu.edu (www.frc.ri.cmu.edu)|128.2.205.32|:80... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```

It seems that the script attempts to access two links from the site www.frc.ri.cmu.edu and both of them require a username and password to enter. Therefore the data in inaccessible.

Can you provide a way to access the data somehow? :)
Thank you very much!

**Comment by shichaoy** [comment]
Hi, thanks for the interest in the work. I think this is due to CMU FRC center sever change starting from 2019. I put the dataset temporarily in google drive. Please see download_data.sh to put them in corresponding folder. I will update the sh file when I find a stable position.    https://drive.google.com/drive/folders/1cfQYQMkU1cZn6e4hPsgGyYwvKfh7gYV7?usp=sharing

**Comment by GalAvineri** [comment]
Thank you very much!
And thank you for the quick response :)

I'll close this as this is resolved than :)
