### ISSUE TITLE
process has died

### ISSUE THREAD

**Issue by hitzhang** [shichaoy/pop_up_slam#8]
started core service [/rosout]
process[world_to_odominit-2]: started with pid [8793]
process[planar_test-3]: started with pid [8794]
process[tf_to_odom-4]: started with pid [8801]
process[rosbag-5]: started with pid [8802]
process[rviz-6]: started with pid [8804]
[planar_test-3] process has died [pid 8794, exit code -11, cmd /home/zhang/workspace/popup_ws/devel/lib/pop_planar_slam/planar_test /image:=/mono/image_mono /camera_info:=/mono/camera_info __name:=planar_test __log:=/home/zhang/.ros/log/dc7a796c-2431-11e9-885b-b083feb6fccb/planar_test-3.log].
log file: /home/zhang/.ros/log/dc7a796c-2431-11e9-885b-b083feb6fccb/planar_test-3*.log
Warning: TF_OLD_DATA ignoring data from the past for frame odom_init at time 1.34184e+09 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-indigo-tf2-0.5.18/src/buffer_core.cpp
[rosbag-5] process has finished cleanly
log file: /home/zhang/.ros/log/dc7a796c-2431-11e9-885b-b083feb6fccb/rosbag-5*.log

**Comment by shichaoy** [comment]
Hi, it exits before the actual calling img_callback_cnn_crf() (See main_3d.cpp), because if it calls, there will be output streams.  So I guess  ```plane_slam planar(n)``` causes the error.  In the constructor, most probably   ```pop_up_obj->Init_python()``` brings the error. Make sure you compile package  ```pop_up_python  numpy_opencv  python_module ```      You can ```catkin_make --only-pkg-with-deps packname```

Can you further check around this?   it is easier for me to solve if you can locate the error more precisely.

**Comment by izengpan** [comment]
I have met the same problem. And I have checked that after compiling the packages you mentioned before, the error still exist...
